// flow-typed signature: 8843b0fd9f12c68a2318c7bd47235b69
// flow-typed version: <<STUB>>/electron-reload_v^1.2.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'electron-reload'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'electron-reload' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'electron-reload/main' {
  declare module.exports: any;
}

// Filename aliases
declare module 'electron-reload/main.js' {
  declare module.exports: $Exports<'electron-reload/main'>;
}
