// flow-typed signature: f023722b1732624f1d6b07f14978c4ec
// flow-typed version: <<STUB>>/react-html-parser_v^1.0.3/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-html-parser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-html-parser' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-html-parser/demo/dist/app' {
  declare module.exports: any;
}

declare module 'react-html-parser/demo/server' {
  declare module.exports: any;
}

declare module 'react-html-parser/demo/src/js/actions' {
  declare module.exports: any;
}

declare module 'react-html-parser/demo/src/js/components/Content' {
  declare module.exports: any;
}

declare module 'react-html-parser/demo/src/js/components/Editor' {
  declare module.exports: any;
}

declare module 'react-html-parser/demo/src/js/components/Header' {
  declare module.exports: any;
}

declare module 'react-html-parser/demo/src/js/components/Html' {
  declare module.exports: any;
}

declare module 'react-html-parser/demo/src/js/containers/App' {
  declare module.exports: any;
}

declare module 'react-html-parser/demo/src/js/data/initialState' {
  declare module.exports: any;
}

declare module 'react-html-parser/demo/src/js/index' {
  declare module.exports: any;
}

declare module 'react-html-parser/demo/src/js/reducers' {
  declare module.exports: any;
}

declare module 'react-html-parser/dist/react-html-parser' {
  declare module.exports: any;
}

declare module 'react-html-parser/dist/react-html-parser.min' {
  declare module.exports: any;
}

declare module 'react-html-parser/lib/dom/attributes/BooleanAttributes' {
  declare module.exports: any;
}

declare module 'react-html-parser/lib/dom/attributes/ReactAttributes' {
  declare module.exports: any;
}

declare module 'react-html-parser/lib/dom/elements/VoidElements' {
  declare module.exports: any;
}

declare module 'react-html-parser/lib/elementTypes/index' {
  declare module.exports: any;
}

declare module 'react-html-parser/lib/elementTypes/StyleElementType' {
  declare module.exports: any;
}

declare module 'react-html-parser/lib/elementTypes/TagElementType' {
  declare module.exports: any;
}

declare module 'react-html-parser/lib/elementTypes/TextElementType' {
  declare module.exports: any;
}

declare module 'react-html-parser/lib/elementTypes/UnsupportedElementType' {
  declare module.exports: any;
}

declare module 'react-html-parser/lib/HtmlParser' {
  declare module.exports: any;
}

declare module 'react-html-parser/lib/index' {
  declare module.exports: any;
}

declare module 'react-html-parser/lib/utils/GeneratePropsFromAttributes' {
  declare module.exports: any;
}

declare module 'react-html-parser/lib/utils/HtmlAttributesToReact' {
  declare module.exports: any;
}

declare module 'react-html-parser/lib/utils/InlineStyleToObject' {
  declare module.exports: any;
}

declare module 'react-html-parser/lib/utils/ProcessNodes' {
  declare module.exports: any;
}

declare module 'react-html-parser/lib/utils/TransformTagName' {
  declare module.exports: any;
}

declare module 'react-html-parser/src/dom/attributes/BooleanAttributes' {
  declare module.exports: any;
}

declare module 'react-html-parser/src/dom/attributes/ReactAttributes' {
  declare module.exports: any;
}

declare module 'react-html-parser/src/dom/elements/VoidElements' {
  declare module.exports: any;
}

declare module 'react-html-parser/src/elementTypes/index' {
  declare module.exports: any;
}

declare module 'react-html-parser/src/elementTypes/StyleElementType' {
  declare module.exports: any;
}

declare module 'react-html-parser/src/elementTypes/TagElementType' {
  declare module.exports: any;
}

declare module 'react-html-parser/src/elementTypes/TextElementType' {
  declare module.exports: any;
}

declare module 'react-html-parser/src/elementTypes/UnsupportedElementType' {
  declare module.exports: any;
}

declare module 'react-html-parser/src/HtmlParser' {
  declare module.exports: any;
}

declare module 'react-html-parser/src/index' {
  declare module.exports: any;
}

declare module 'react-html-parser/src/utils/GeneratePropsFromAttributes' {
  declare module.exports: any;
}

declare module 'react-html-parser/src/utils/HtmlAttributesToReact' {
  declare module.exports: any;
}

declare module 'react-html-parser/src/utils/InlineStyleToObject' {
  declare module.exports: any;
}

declare module 'react-html-parser/src/utils/ProcessNodes' {
  declare module.exports: any;
}

declare module 'react-html-parser/src/utils/TransformTagName' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-html-parser/demo/dist/app.js' {
  declare module.exports: $Exports<'react-html-parser/demo/dist/app'>;
}
declare module 'react-html-parser/demo/server.js' {
  declare module.exports: $Exports<'react-html-parser/demo/server'>;
}
declare module 'react-html-parser/demo/src/js/actions.js' {
  declare module.exports: $Exports<'react-html-parser/demo/src/js/actions'>;
}
declare module 'react-html-parser/demo/src/js/components/Content.js' {
  declare module.exports: $Exports<'react-html-parser/demo/src/js/components/Content'>;
}
declare module 'react-html-parser/demo/src/js/components/Editor.js' {
  declare module.exports: $Exports<'react-html-parser/demo/src/js/components/Editor'>;
}
declare module 'react-html-parser/demo/src/js/components/Header.js' {
  declare module.exports: $Exports<'react-html-parser/demo/src/js/components/Header'>;
}
declare module 'react-html-parser/demo/src/js/components/Html.js' {
  declare module.exports: $Exports<'react-html-parser/demo/src/js/components/Html'>;
}
declare module 'react-html-parser/demo/src/js/containers/App.js' {
  declare module.exports: $Exports<'react-html-parser/demo/src/js/containers/App'>;
}
declare module 'react-html-parser/demo/src/js/data/initialState.js' {
  declare module.exports: $Exports<'react-html-parser/demo/src/js/data/initialState'>;
}
declare module 'react-html-parser/demo/src/js/index.js' {
  declare module.exports: $Exports<'react-html-parser/demo/src/js/index'>;
}
declare module 'react-html-parser/demo/src/js/reducers.js' {
  declare module.exports: $Exports<'react-html-parser/demo/src/js/reducers'>;
}
declare module 'react-html-parser/dist/react-html-parser.js' {
  declare module.exports: $Exports<'react-html-parser/dist/react-html-parser'>;
}
declare module 'react-html-parser/dist/react-html-parser.min.js' {
  declare module.exports: $Exports<'react-html-parser/dist/react-html-parser.min'>;
}
declare module 'react-html-parser/lib/dom/attributes/BooleanAttributes.js' {
  declare module.exports: $Exports<'react-html-parser/lib/dom/attributes/BooleanAttributes'>;
}
declare module 'react-html-parser/lib/dom/attributes/ReactAttributes.js' {
  declare module.exports: $Exports<'react-html-parser/lib/dom/attributes/ReactAttributes'>;
}
declare module 'react-html-parser/lib/dom/elements/VoidElements.js' {
  declare module.exports: $Exports<'react-html-parser/lib/dom/elements/VoidElements'>;
}
declare module 'react-html-parser/lib/elementTypes/index.js' {
  declare module.exports: $Exports<'react-html-parser/lib/elementTypes/index'>;
}
declare module 'react-html-parser/lib/elementTypes/StyleElementType.js' {
  declare module.exports: $Exports<'react-html-parser/lib/elementTypes/StyleElementType'>;
}
declare module 'react-html-parser/lib/elementTypes/TagElementType.js' {
  declare module.exports: $Exports<'react-html-parser/lib/elementTypes/TagElementType'>;
}
declare module 'react-html-parser/lib/elementTypes/TextElementType.js' {
  declare module.exports: $Exports<'react-html-parser/lib/elementTypes/TextElementType'>;
}
declare module 'react-html-parser/lib/elementTypes/UnsupportedElementType.js' {
  declare module.exports: $Exports<'react-html-parser/lib/elementTypes/UnsupportedElementType'>;
}
declare module 'react-html-parser/lib/HtmlParser.js' {
  declare module.exports: $Exports<'react-html-parser/lib/HtmlParser'>;
}
declare module 'react-html-parser/lib/index.js' {
  declare module.exports: $Exports<'react-html-parser/lib/index'>;
}
declare module 'react-html-parser/lib/utils/GeneratePropsFromAttributes.js' {
  declare module.exports: $Exports<'react-html-parser/lib/utils/GeneratePropsFromAttributes'>;
}
declare module 'react-html-parser/lib/utils/HtmlAttributesToReact.js' {
  declare module.exports: $Exports<'react-html-parser/lib/utils/HtmlAttributesToReact'>;
}
declare module 'react-html-parser/lib/utils/InlineStyleToObject.js' {
  declare module.exports: $Exports<'react-html-parser/lib/utils/InlineStyleToObject'>;
}
declare module 'react-html-parser/lib/utils/ProcessNodes.js' {
  declare module.exports: $Exports<'react-html-parser/lib/utils/ProcessNodes'>;
}
declare module 'react-html-parser/lib/utils/TransformTagName.js' {
  declare module.exports: $Exports<'react-html-parser/lib/utils/TransformTagName'>;
}
declare module 'react-html-parser/src/dom/attributes/BooleanAttributes.js' {
  declare module.exports: $Exports<'react-html-parser/src/dom/attributes/BooleanAttributes'>;
}
declare module 'react-html-parser/src/dom/attributes/ReactAttributes.js' {
  declare module.exports: $Exports<'react-html-parser/src/dom/attributes/ReactAttributes'>;
}
declare module 'react-html-parser/src/dom/elements/VoidElements.js' {
  declare module.exports: $Exports<'react-html-parser/src/dom/elements/VoidElements'>;
}
declare module 'react-html-parser/src/elementTypes/index.js' {
  declare module.exports: $Exports<'react-html-parser/src/elementTypes/index'>;
}
declare module 'react-html-parser/src/elementTypes/StyleElementType.js' {
  declare module.exports: $Exports<'react-html-parser/src/elementTypes/StyleElementType'>;
}
declare module 'react-html-parser/src/elementTypes/TagElementType.js' {
  declare module.exports: $Exports<'react-html-parser/src/elementTypes/TagElementType'>;
}
declare module 'react-html-parser/src/elementTypes/TextElementType.js' {
  declare module.exports: $Exports<'react-html-parser/src/elementTypes/TextElementType'>;
}
declare module 'react-html-parser/src/elementTypes/UnsupportedElementType.js' {
  declare module.exports: $Exports<'react-html-parser/src/elementTypes/UnsupportedElementType'>;
}
declare module 'react-html-parser/src/HtmlParser.js' {
  declare module.exports: $Exports<'react-html-parser/src/HtmlParser'>;
}
declare module 'react-html-parser/src/index.js' {
  declare module.exports: $Exports<'react-html-parser/src/index'>;
}
declare module 'react-html-parser/src/utils/GeneratePropsFromAttributes.js' {
  declare module.exports: $Exports<'react-html-parser/src/utils/GeneratePropsFromAttributes'>;
}
declare module 'react-html-parser/src/utils/HtmlAttributesToReact.js' {
  declare module.exports: $Exports<'react-html-parser/src/utils/HtmlAttributesToReact'>;
}
declare module 'react-html-parser/src/utils/InlineStyleToObject.js' {
  declare module.exports: $Exports<'react-html-parser/src/utils/InlineStyleToObject'>;
}
declare module 'react-html-parser/src/utils/ProcessNodes.js' {
  declare module.exports: $Exports<'react-html-parser/src/utils/ProcessNodes'>;
}
declare module 'react-html-parser/src/utils/TransformTagName.js' {
  declare module.exports: $Exports<'react-html-parser/src/utils/TransformTagName'>;
}
